config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :agencies

  resources :accounts

  resources :movements

end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :agency
    has_many :movements

    validates :number, presence: true, length: { minimum: 7, maximum: 7}
    validates :number, uniqueness: true
    validates :agencia, presence: true
    validates :limit, presence: true
    
end

app/models/agency.rb
class Agency < ApplicationRecord
    has_many :accounts

    validates :number, presence: true, length: { minimum: 4, maximum: 4}
    validates :number, uniqueness: true
    validates :address, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movement.rb
class Movement < ApplicationRecord
    belongs_to :user
    belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  has_many :movements
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

    def new
        @account = Account.new
    end

    def edit
        @account = Account.find(params[:id])
    end

    def create
        @account = Account.new(account_params)
        numero_agencia = @account.agencia
        @account.agency = Agency.find_by(number: numero_agencia)
        if @account.save
            flash[:notice] = "Conta cadastrada com sucesso"
            redirect_to accounts_path
        else
            flash[:danger] = "Conta já cadastrada ou campos preenchidos incorretamentes"
            render 'new'
        end
    end

    def index
        @accounts = Account.all
    end

    def show
        @account = Account.find(params[:id])
    end

    def update
        @account = Account.find(params[:id])
        if @account.update(account_params)
            flash[:notice] = "Conta atualizada com sucesso"
            redirect_to account_path(@account)
        else
            render 'edit'
        end
    end

    def destroy
        @account = Account.find(params[:id])
        @account.destroy
        flash[:notice] = "Conta excluida com sucesso"
        redirect_to accounts_path
    end

    def deposito
        
    end

    private
    def account_params
        params.require(:account).permit(:number, :limit, :agencia)
    end

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
    def new
        @agency = Agency.new
    end

    def edit
        @agency = Agency.find(params[:id])
    end

    def create
        @agency = Agency.new(agency_params)
        if @agency.save
            flash[:notice] = "Agencia cadastrada com sucesso"
            redirect_to agencies_path
        else
            flash[:danger] = "Agencia já cadastrada ou campos preenchidos incorretamentes"
            render 'new'
        end
    end

    def index
        @agencies = Agency.all
    end

    def show
        @agency = Agency.find(params[:id])
    end

    def update
        @agency = Agency.find(params[:id])
        if @agency.update(agency_params)
            flash[:notice] = "Agencia atualizada com sucesso"
            redirect_to agencies_path
        else
            render 'edit'
        end
    end

    def destroy
        @agency = Agency.find(params[:id])
        @agency.destroy
        flash[:notice] = "Agência excluída com sucesso"
        redirect_to agencies_path
    end

    private
    def agency_params
        params.require(:agency).permit(:number, :address)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    
    end

end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
    def new
        @movement = Movement.new
    end

    def create
        @movement = Movement.new(movement_params)
        @movement.user = current_user
        @movement.account = Account.find_by(number: @movement.conta_raiz)
        @account = Account.find_by(number: @movement.conta_alvo)
        target = Account.find_by(number: @movement.conta_alvo)
        if @movement.movement_type == 'Depósito'
            @movement.account.limit = @movement.account.limit + @movement.amount
            @movement.account.save
        end
        if @movement.movement_type == 'Saque'
            if @movement.amount < @movement.account.limit
                @movement.account.limit = @movement.account.limit - @movement.amount
                @movement.account.save
            else
                flash[:notice] = "Saldo insuficiente" 
                redirect_to movements_path and return
            end
        end
        if @movement.movement_type == 'Transferência'
            if @movement.amount < @movement.account.limit 
                @movement.account.limit = @movement.account.limit - @movement.amount
                @movement.account.save
                @account.limit = @account.limit + @movement.amount
                @account.save
            else
                flash[:notice] = "Saldo insuficiente" 
                redirect_to movements_path and return
            end
        end
        if @movement.save
            flash[:notice] = "Movimentação realizada com sucesso"
            redirect_to movements_path
        else
            render 'new'
        end
    end

    def index
        @movements = Movement.all
    end

    def show
        @movement = Movement.find(params[:id])
    end


    private
    def movement_params
        params.require(:movement).permit(:movement_type, :amount, :conta_raiz, :conta_alvo)
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
    before_filter :configure_permitted_parameters

    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.erb
<h1>Atualize sua conta</h1>

<% contas = Account.all %>

<div class="panel-body">


<%= form_for @account do |f| %>
    
    <div class="form-group">
        <%= f.label :agencia %>
        <%= f.text_field :agencia, autofocus: true, class: 'form-control' %>
    </div> 
    
    <div class="form-group">
        <%= f.label :number %>
        <%= f.text_field :number, autofocus: true, class: 'form-control' %>
    </div> 
    
     <div class="form-group">
        <%= f.label :limit %>
        <%= f.number_field :limit, class: 'form-control', :step => "0.01" %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>

<% end %>

</div>

app/views/accounts/index.html.erb
<h1>Minhas Contas</h1>

<body>

    <% @accounts.each do |account| %>
        <div class="card-custom">
            
            <div class="card-body padding-custom">
                <h5 class="card-title"><b>Número:</b> <%= account.number %></h5>
                <p class="card-text"><b>Saldo:</b> R$ <%= account.limit %> </p>
                <%= link_to "Detalhes", account_path(account), :class=>"btn btn-primary" %>
            </div>

        </div></br>
    <% end %>

    <%= link_to "Cadastrar Conta", new_account_path, :class=>"btn btn-primary"  %>
    </br>

</body><br>

app/views/accounts/new.html.erb
<h1>Cadastre sua conta</h1>

<% contas = Agency.all %>

<div class="panel-body">


<%= form_for @account do |f| %>
    
    <div class="form-group">
        <%= f.label :agencia %>
        <%= f.text_field :agencia, autofocus: true, class: 'form-control' %>
    </div> 
    
    <div class="form-group">
        <%= f.label :number %>
        <%= f.text_field :number, autofocus: true, class: 'form-control' %>
    </div> 
    
     <div class="form-group">
        <%= f.label :limit %>
        <%= f.number_field :limit, class: 'form-control', :step => "0.01" %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>

<% end %>

</div>

app/views/accounts/show.html.erb
<h1 align="center">Minha Conta</h1>

<div class="card-custom">
    <div class="padding-custom">
        <h5 class="card-title"><b>Número:</b> <%= @account.number %></h5>
        <p class="card-text"><b>Agência:</b> <%= @account.agency.number %> </p>
        <p class="card-text"><b>Endereço:</b> <%= @account.agency.address %> </p>
        <p class="card-text"><b>Saldo:</b> R$ <%= @account.limit %> </p>
        <%= link_to "Editar", edit_account_url(@account), :class=>"btn btn-primary" %>
        <%= link_to "Deletar", account_path(@account), method: :delete, data: {confirm: "Você tem certeza?"}, :class=>"btn btn-danger" %>
    </div>
</div></br>

app/views/agencies/edit.html.erb
<h1>Editar Agência</h1>

<div class="panel-body">

<%= form_for @agency do |f| %>

    <div class="form-group">
        <%= f.label :number %>
        <%= f.text_field :number, autofocus: true, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>

<% end %>

</div>

app/views/agencies/index.html.erb
<h1>Minhas Agências</h1>

<body>

    <% @agencies.each do |agency| %>
        <div class="card-custom">
            
            <div class="card-body padding-custom">
                <h5 class="card-title"><b>Número:</b> <%= agency.number %></h5>
                <p class="card-text"><b>Endereço:</b> <%= agency.address %> </p>
                <%= link_to "Editar", edit_agency_url(agency), :class=>"btn btn-primary" %>
                <%= link_to "Deletar", agency_path(agency), method: :delete, data: {confirm: "Você tem certeza?"}, :class=>"btn btn-danger" %>
            </div>

        </div></br>
    <% end %>

    <%= link_to "Cadastrar Agência", new_agency_path, :class=>"btn btn-primary"  %>
    </br>

</body><br>

app/views/agencies/new.html.erb
<h1>HI MOTHERFUCKER!</h1>

<div class="panel-body">

<%= form_for @agency do |f| %>

    <div class="form-group">
        <%= f.label :number %>
        <%= f.text_field :number, autofocus: true, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>

<% end %>

</div>

app/views/home/index.html.erb
<h1>Meu histórico</h1>

<% @movements = Movement.all %>

<body>

    <% @movements.each do |movement| %>
        <% if current_user.id == movement.user_id %>
            <div class="card-custom">
                
                <div class="card-body padding-custom">
                    <h5 class="card-title"><b>Conta:</b> <%= movement.conta_raiz %></h5>
                    <p class="card-text"><b>Tipo de Movimentação:</b> <%= movement.movement_type %> </p>
                    <% if movement.movement_type == 'Transferência' %>
                        <p class="card-text"><b>Conta beneficiada:</b> <%= movement.conta_alvo %> </p>
                    <% end %>    
                    <p class="card-text"><b>Valor:</b> R$ <%= movement.amount %> </p>
                    <p class="card-text"><b>Data:</b> <%= movement.created_at %> </p>
                    
                </div>

            </div></br>
        <% end %>
    <% end %>

</body><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Transfersol" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" >Transfersol</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

        <% if current_user%>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Olá, <%= current_user.first_name %></h3>
            <ul class="nav nav-list">
              <li><%= link_to "Agências", agencies_path  %></li>
              <li><%= link_to "Contas", accounts_path  %></li>
              <li><%= link_to "Movimentações", movements_path  %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-danger'%></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <% end %>
      </div><!--/row-->

      <footer>
        <p>&copy; Atos Software 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/movements/index.html.erb
<h1>Minhas Movimentações</h1>

<body>

    <% @movements.each do |movement| %>
        <% if current_user.id == movement.user_id %>
            <div class="card-custom">
                
                <div class="card-body padding-custom">
                    <h5 class="card-title"><b>Conta:</b> <%= movement.conta_raiz %></h5>
                    <p class="card-text"><b>Tipo de Movimentação:</b> <%= movement.movement_type %> </p>
                    <% if movement.movement_type == 'Transferência' %>
                        <p class="card-text"><b>Conta beneficiada:</b> <%= movement.conta_alvo %> </p>
                    <% end %>    
                    <p class="card-text"><b>Valor:</b> R$ <%= movement.amount %> </p>
                    <p class="card-text"><b>Data:</b> <%= movement.created_at %> </p>
                    
                </div>

            </div></br>
        <% end %>
    <% end %>

    <%= link_to "Realizar Movimentação", new_movement_path, :class=>"btn btn-primary"  %>
    </br>

</body><br>

app/views/movements/new.html.erb
<h1>Realize sua transação</h1>

<div class="panel-body">

<%= form_for @movement do |f| %>

    <div class="form-group">
        <%= f.label :conta_raiz %>
        <%= f.text_field :conta_raiz, autofocus: true, class: 'form-control' %>
    </div> 

    <div class"form group">
        <%= f.label :movement_type %>
        <%= f.select :movement_type, ['Depósito', 'Saque', 'Transferência'], {}, class: 'form-control' %>
    </div></br>

    <div class="form-group">
        <%= f.label :conta_alvo %>
        <%= f.text_field :conta_alvo, autofocus: true, class: 'form-control' %>
    </div> 

    <div class="form-group">
        <%= f.label :amount %>
        <%= f.number_field :amount, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>

<% end %>

</div>